In [1]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class HuskyControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the HuskyJointController.
        This class is responsible for controlling the Husky robot's joints.
        '''
        super().__init__("HuskyJointController")

        if SIM == True:
            self.joint_group_command = self.create_publisher("Husky/joint_group_command/sim", joint_group_command_t)
            self.task_space_command = self.create_publisher("Husky/cartesian_command/sim", task_space_command_t)

            self.state = self.create_listener("Husky/joint_states/sim", joint_state_t)

controller = HuskyControllerNode()

[WARNING] [17:34:33.676688] - No global configuration provided. Using default system configuration.
[INFO] [17:34:33.680455] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/HuskyJointController_1b928dbb-f466-4144-8311-de5ad07d1970' with registry.
[INFO] [17:34:33.683302] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/HuskyJointController_1b928dbb-f466-4144-8311-de5ad07d1970' with registry.
[INFO] [17:34:33.687021] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/HuskyJointController_1b928dbb-f466-4144-8311-de5ad07d1970' with registry.
[ERROR] [17:34:33.688146] - Couldn't load config for other 'HuskyJointController'
[OK] [17:34:33.689719] - setup publisher Husky/joint_group_command/sim[joint_group_command_t]
[OK] [17:34:33.691384] - setup publisher Husky/cartesian_command/sim[task_space_command_t]
[OK] [17:34:33.693991] - subscribed to Husky/joint_states/sim[joint_state_t]


None


---

# Joint Group Control

In [15]:
# FORWARDS
joint_command = [5, 5, 5, 5] # front left, front right, back left, back right
# Velocity Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "wheels"))

In [14]:
# BACKWARDS
joint_command = [-5, -5, -5, -5] # front left, front right, back left, back right
# Velocity Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "wheels"))

In [16]:
# STOP
joint_command = [0, 0, 0, 0] # front left, front right, back left, back right
# Velocity Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "wheels"))

---

# Joint States

In [9]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['front_left_wheel',
  'front_right_wheel',
  'rear_left_wheel',
  'rear_right_wheel'],
 array([-0.95493975,  0.6826147 ,  7.97192306, -9.61348529]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]))